export const SELECTORS = {
  header: {
    title: '[data-testid="app-title"]',
  },
  actionBar: {
    searchBar: '[data-testid="search-bar"]',
    sortSelect: '[data-testid="sort-select"]',
    addRecipeBtn: '[data-testid="add-recipe-btn"]',
  },
  tagManager: {
    container: '[data-testid="tags-container"]',
    pill: '[data-testid="tag-pill"]',
    filterPill: '[data-testid="tag-filter-pill"]',
    tagError: '[data-testid="tag-error"]',
    tagInput: '[data-testid="tag-input"]',
    tagEditBtn: '[data-testid="tag-edit-btn"]',
    tagDeleteBtn: '[data-testid="tag-delete-btn"]',
    deleteTagDialogConfirm: '[data-testid="delete-tag-dialog-confirm"]',
    deleteTagDialogCancel: '[data-testid="delete-tag-dialog-cancel"]',
  },
  recipeGrid: {
    card: '[data-testid="recipe-card"]',
    cardName: '[data-testid="recipe-card-name"]',
    cardTag: '[data-testid="recipe-card-tag"]',
    cardImage: '[data-testid="recipe-card-image"]',
    cardImagePlaceholder: '[data-testid="recipe-card-image-placeholder"]',
    emptyState: '[data-testid="empty-grid-state"]',
  },
  recipeModal: {
    saveBtn: '[data-testid="modal-save-btn"]',
    cancelBtn: '[data-testid="modal-cancel-btn"]',
    editBtn: '[data-testid="recipe-card-edit-btn"]',
    deleteBtn: '[data-testid="modal-delete-btn"]',
    fetchOgBtn: '[data-testid="fetch-og-btn"]',
    modalOverlay: '[data-slot="dialog-overlay"]',
    viewCloseBtn: '[data-testid="modal-view-close-btn"]',
    recipeLink: '[data-testid="modal-recipe-link"]',
    nameInput: '[data-testid="recipe-name-input"]',
    linkInput: '[data-testid="recipe-link-input"]',
    imageInput: '[data-testid="recipe-image-input"]',
    notesInput: '[data-testid="recipe-notes-input"]',
    modalImage: '[data-testid="modal-image"]',
    modalImagePlaceholder: '[data-testid="modal-image-placeholder"]',
    tagInput: '[data-testid="tag-input"]',
    removeTagChip: '[data-testid="remove-tag-chip"]',
    tagDuplicateError: '[data-testid="modal-tag-error"]',
    linkError: '[data-testid="link-error"]',
    imageUrlError: '[data-testid="image-url-error"]',
    ogError: '[data-testid="error-message"]',
    unsavedChangesConfirmDiscard: '[data-testid="unsaved-changes-confirm"]',
    unsavedChangesCancelDiscard: '[data-testid="unsaved-changes-cancel"]',
    discardChangesDialog: '[data-testid="discard-changes-dialog"]',
    discardChangesConfirmBtn: '[data-testid="unsaved-changes-confirm"]',
    keepEditingBtn: '[data-testid="unsaved-changes-cancel"]',
    deleteConfirmBtn: '[data-testid="delete-confirm-btn"]',
    deleteCancelBtn: '[data-testid="delete-cancel-btn"]',
  },
} as const
